-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity toplevel_core_B is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_out_b_0_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    x_out_b_1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    x_out_b_2_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    V1_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    V2_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    I1_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    I2_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    I3_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    Vp_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    Vs_dab1_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    i_in_port_model_of_a_V : IN STD_LOGIC_VECTOR (71 downto 0);
    i_in_port_model_of_c_V : IN STD_LOGIC_VECTOR (71 downto 0);
    i_out_port_model_to_a_V : OUT STD_LOGIC_VECTOR (71 downto 0);
    i_out_port_model_to_c_V : OUT STD_LOGIC_VECTOR (71 downto 0) );
end;


architecture behav of toplevel_core_B is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "toplevel_core_B,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2104-2L-e,HLS_INPUT_CLOCK=70.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=36.478168,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=398,HLS_SYN_FF=522,HLS_SYN_LUT=11455,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_EE : STD_LOGIC_VECTOR (7 downto 0) := "11101110";
    constant ap_const_lv8_77 : STD_LOGIC_VECTOR (7 downto 0) := "01110111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_115 : STD_LOGIC_VECTOR (8 downto 0) := "100010101";
    constant ap_const_lv9_27 : STD_LOGIC_VECTOR (8 downto 0) := "000100111";
    constant ap_const_lv9_9E : STD_LOGIC_VECTOR (8 downto 0) := "010011110";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv109_1057D9D428 : STD_LOGIC_VECTOR (108 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001000001010111110110011101010000101000";
    constant ap_const_lv109_1052A0AAB6 : STD_LOGIC_VECTOR (108 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001000001010010101000001010101010110110";
    constant ap_const_lv88_DAEB : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001101101011101011";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv110_20AA7A7EDE : STD_LOGIC_VECTOR (109 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010000010101010011110100111111011011110";
    constant ap_const_lv88_DAA5 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001101101010100101";
    constant ap_const_lv118_33190708F18C : STD_LOGIC_VECTOR (117 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001100110001100100000111000010001111000110001100";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv47_0 : STD_LOGIC_VECTOR (46 downto 0) := "00000000000000000000000000000000000000000000000";
    constant ap_const_lv104_1CEF684BDA12F60 : STD_LOGIC_VECTOR (103 downto 0) := "00000000000000000000000000000000000000000000000111001110111101101000010010111101101000010010111101100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv60_682AAAAAAAAAAC0 : STD_LOGIC_VECTOR (59 downto 0) := "011010000010101010101010101010101010101010101010101011000000";
    constant ap_const_lv53_B92F684BDA130 : STD_LOGIC_VECTOR (52 downto 0) := "01011100100101111011010000100101111011010000100110000";
    constant ap_const_lv48_400000000000 : STD_LOGIC_VECTOR (47 downto 0) := "010000000000000000000000000000000000000000000000";
    constant ap_const_lv59_1CEF684BDA12F60 : STD_LOGIC_VECTOR (58 downto 0) := "00111001110111101101000010010111101101000010010111101100000";
    constant ap_const_lv48_C00000000000 : STD_LOGIC_VECTOR (47 downto 0) := "110000000000000000000000000000000000000000000000";
    constant ap_const_lv59_0 : STD_LOGIC_VECTOR (58 downto 0) := "00000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv59_631097B425ED0A0 : STD_LOGIC_VECTOR (58 downto 0) := "11000110001000010010111101101000010010111101101000010100000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv60_97D555555555540 : STD_LOGIC_VECTOR (59 downto 0) := "100101111101010101010101010101010101010101010101010101000000";
    constant ap_const_lv53_146D097B425ED0 : STD_LOGIC_VECTOR (52 downto 0) := "10100011011010000100101111011010000100101111011010000";
    constant ap_const_lv131_lc_1 : STD_LOGIC_VECTOR (130 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111101101111010100101111011010000100101111011010000100110000000";
    constant ap_const_lv131_lc_2 : STD_LOGIC_VECTOR (130 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010010000101011010000100101111011010000100101111011010000000";
    constant ap_const_lv154_lc_3 : STD_LOGIC_VECTOR (153 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv92_0 : STD_LOGIC_VECTOR (91 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv32_A3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100011";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv140_lc_4 : STD_LOGIC_VECTOR (139 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111101011100101011111010101010101010101010101010101010101000000000000000";
    constant ap_const_lv140_lc_5 : STD_LOGIC_VECTOR (139 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010100010110000101010101010101010101010101010101010110000000000000000";
    constant ap_const_lv164_lc_3 : STD_LOGIC_VECTOR (163 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv137_lc_6 : STD_LOGIC_VECTOR (136 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010001011100000100100100100100100100100100100100100101000000000000";
    constant ap_const_lv160_lc_3 : STD_LOGIC_VECTOR (159 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv133_lc_7 : STD_LOGIC_VECTOR (132 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001001000010101101000010010111101101000010010111101101100000000";
    constant ap_const_lv133_lc_8 : STD_LOGIC_VECTOR (132 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001101011110000010010111101101000010010111101101000011000000000";
    constant ap_const_lv157_lc_3 : STD_LOGIC_VECTOR (156 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010010110010100101110100";
    constant ap_const_lv119_500000000000 : STD_LOGIC_VECTOR (118 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010100000000000000000000000000000000000000000000";
    constant ap_const_lv118_3FEB8BA946A8 : STD_LOGIC_VECTOR (117 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001111111110101110001011101010010100011010101000";
    constant ap_const_lv98_3594739 : STD_LOGIC_VECTOR (97 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000011010110010100011100111001";
    constant ap_const_lv117_1FFAE218FF01 : STD_LOGIC_VECTOR (116 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000111111111101011100010000110001111111100000001";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal counter1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal counter2 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal b_components_V_0 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal b_components_V_1 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal V1past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal I1past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal I2past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal I3past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal V2past_dab1_V : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln57_fu_334_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln66_fu_370_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_75_fu_1668_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_78_fu_1712_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_34_fu_1115_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_44_fu_1266_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_61_fu_1476_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_72_fu_1599_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_52_fu_1377_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_6_fu_532_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal p_Val2_18_fu_722_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal icmp_ln50_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln50_fu_320_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln59_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal nph_fu_356_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln52_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln703_fu_398_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal add_ln703_fu_398_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_fu_416_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_1_fu_412_p1 : STD_LOGIC_VECTOR (108 downto 0);
    signal sext_ln1118_2_fu_422_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_3_fu_426_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_4_fu_430_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_5_fu_434_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_9_fu_438_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_fu_416_p2 : STD_LOGIC_VECTOR (108 downto 0);
    signal r_V_9_fu_438_p2 : STD_LOGIC_VECTOR (108 downto 0);
    signal sext_ln1192_fu_448_p1 : STD_LOGIC_VECTOR (109 downto 0);
    signal sext_ln700_fu_444_p1 : STD_LOGIC_VECTOR (109 downto 0);
    signal sext_ln1118_6_fu_466_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_7_fu_470_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_10_fu_474_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_7_fu_470_p1 : STD_LOGIC_VECTOR (87 downto 0);
    signal r_V_10_fu_474_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal sext_ln1192_1_fu_480_p1 : STD_LOGIC_VECTOR (109 downto 0);
    signal add_ln700_fu_460_p2 : STD_LOGIC_VECTOR (109 downto 0);
    signal ret_V_22_fu_488_p2 : STD_LOGIC_VECTOR (109 downto 0);
    signal tmp_1_fu_494_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1192_2_fu_484_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_1_fu_456_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_fu_452_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_4_fu_508_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_fu_514_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_2_fu_520_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_5_fu_504_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_fu_528_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_11_fu_539_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_12_fu_545_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_11_fu_539_p2 : STD_LOGIC_VECTOR (108 downto 0);
    signal r_V_12_fu_545_p2 : STD_LOGIC_VECTOR (109 downto 0);
    signal sext_ln700_1_fu_551_p1 : STD_LOGIC_VECTOR (109 downto 0);
    signal r_V_13_fu_569_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_13_fu_569_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal sext_ln1192_3_fu_575_p1 : STD_LOGIC_VECTOR (109 downto 0);
    signal add_ln700_1_fu_563_p2 : STD_LOGIC_VECTOR (109 downto 0);
    signal ret_V_23_fu_583_p2 : STD_LOGIC_VECTOR (109 downto 0);
    signal tmp_3_fu_589_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1192_5_fu_579_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_4_fu_559_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_3_fu_555_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_5_fu_603_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_1_fu_609_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_4_fu_615_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_11_fu_599_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_1_fu_623_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_14_fu_634_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_15_fu_640_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_14_fu_634_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal r_V_15_fu_640_p2 : STD_LOGIC_VECTOR (87 downto 0);
    signal sext_ln1192_4_fu_650_p1 : STD_LOGIC_VECTOR (88 downto 0);
    signal sext_ln700_2_fu_646_p1 : STD_LOGIC_VECTOR (88 downto 0);
    signal add_ln700_2_fu_662_p2 : STD_LOGIC_VECTOR (88 downto 0);
    signal r_V_16_fu_672_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_16_fu_672_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal sext_ln700_3_fu_668_p1 : STD_LOGIC_VECTOR (117 downto 0);
    signal ret_V_24_fu_682_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal trunc_ln1192_8_fu_678_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_7_fu_658_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_6_fu_654_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_6_fu_698_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_2_fu_704_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_5_fu_710_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_17_fu_688_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_2_fu_718_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal signbit_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln72_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln78_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal signbit_1_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_19_fu_749_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal p_Val2_22_fu_735_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal p_Val2_23_fu_757_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal zext_ln703_fu_763_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln703_1_fu_767_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ret_V_fu_771_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_17_fu_781_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal r_V_17_fu_781_p2 : STD_LOGIC_VECTOR (103 downto 0);
    signal tmp_6_fu_787_p4 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_7_fu_801_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln713_fu_797_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln415_3_fu_809_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal zext_ln152_fu_819_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln152_1_fu_823_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_V_fu_827_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln703_fu_841_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln153_fu_847_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln153_1_fu_851_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_V_5_fu_855_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln703_1_fu_865_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1498_fu_871_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_25_fu_813_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal icmp_ln1498_2_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1498_1_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln164_fu_905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln164_1_fu_897_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal select_ln156_fu_877_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal icmp_ln173_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln169_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln177_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln177_1_fu_931_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal mul_ln703_fu_841_p2 : STD_LOGIC_VECTOR (59 downto 0);
    signal icmp_ln186_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln182_fu_953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln190_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln190_1_fu_965_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal mul_ln703_1_fu_865_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln1118_8_fu_991_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_18_fu_995_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_8_fu_991_p1 : STD_LOGIC_VECTOR (130 downto 0);
    signal select_ln164_fu_911_p3 : STD_LOGIC_VECTOR (58 downto 0);
    signal sext_ln1118_9_fu_1009_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_10_fu_1013_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_11_fu_1017_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_12_fu_1021_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_19_fu_1025_p0 : STD_LOGIC_VECTOR (58 downto 0);
    signal sext_ln1116_1_fu_1001_p1 : STD_LOGIC_VECTOR (129 downto 0);
    signal r_V_19_fu_1025_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_19_fu_1025_p2 : STD_LOGIC_VECTOR (129 downto 0);
    signal r_V_18_fu_995_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal sext_ln1118_13_fu_1031_p1 : STD_LOGIC_VECTOR (130 downto 0);
    signal ret_V_25_fu_1035_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal r_V_20_fu_1049_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal r_V_20_fu_1049_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal sext_ln1118_15_fu_1055_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal sext_ln1193_fu_1041_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal ret_V_5_fu_1059_p2 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_4_fu_1069_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_4_fu_1069_p2 : STD_LOGIC_VECTOR (153 downto 0);
    signal lhs_V_fu_1079_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln703_5_fu_1075_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_fu_1079_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_26_fu_1087_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_8_fu_1103_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_33_fu_1093_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_4_fu_1111_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal select_ln177_fu_945_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal r_V_21_fu_1126_p0 : STD_LOGIC_VECTOR (59 downto 0);
    signal r_V_21_fu_1126_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_21_fu_1126_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal mul_ln1193_fu_1136_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln1193_fu_1136_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln703_6_fu_1132_p1 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln1118_25_fu_1152_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_16_fu_1156_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_17_fu_1160_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_18_fu_1164_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_22_fu_1168_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal ret_V_27_fu_1142_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal r_V_22_fu_1168_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln703_8_fu_1178_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal sext_ln703_7_fu_1174_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal sext_ln1118_19_fu_1192_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_20_fu_1196_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_21_fu_1200_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_23_fu_1204_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_23_fu_1204_p2 : STD_LOGIC_VECTOR (139 downto 0);
    signal sext_ln703_9_fu_1210_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal ret_V_28_fu_1182_p2 : STD_LOGIC_VECTOR (140 downto 0);
    signal ret_V_9_fu_1214_p2 : STD_LOGIC_VECTOR (140 downto 0);
    signal r_V_24_fu_1224_p1 : STD_LOGIC_VECTOR (140 downto 0);
    signal lhs_V_1_fu_1230_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_24_fu_1224_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_1_fu_1230_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_29_fu_1238_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_9_fu_1254_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_43_fu_1244_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_5_fu_1262_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1118_23_fu_1277_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_25_fu_1281_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_26_fu_1287_p0 : STD_LOGIC_VECTOR (58 downto 0);
    signal r_V_26_fu_1287_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_26_fu_1287_p2 : STD_LOGIC_VECTOR (129 downto 0);
    signal sext_ln1118_32_fu_1293_p1 : STD_LOGIC_VECTOR (130 downto 0);
    signal r_V_25_fu_1281_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal ret_V_30_fu_1297_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal r_V_27_fu_1311_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_27_fu_1311_p2 : STD_LOGIC_VECTOR (130 downto 0);
    signal sext_ln1118_33_fu_1317_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal sext_ln1192_5_fu_1303_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal ret_V_12_fu_1321_p2 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_5_fu_1331_p1 : STD_LOGIC_VECTOR (131 downto 0);
    signal mul_ln703_5_fu_1331_p2 : STD_LOGIC_VECTOR (153 downto 0);
    signal lhs_V_2_fu_1341_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln703_11_fu_1337_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_2_fu_1341_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_31_fu_1349_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_10_fu_1365_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_51_fu_1355_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_6_fu_1373_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_28_fu_1384_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_29_fu_1390_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_28_fu_1384_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal r_V_29_fu_1390_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal sext_ln703_12_fu_1396_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal sext_ln703_13_fu_1400_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal r_V_30_fu_1410_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_30_fu_1410_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal ret_V_32_fu_1404_p2 : STD_LOGIC_VECTOR (137 downto 0);
    signal sext_ln703_14_fu_1416_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal ret_V_15_fu_1420_p2 : STD_LOGIC_VECTOR (137 downto 0);
    signal r_V_31_fu_1430_p1 : STD_LOGIC_VECTOR (137 downto 0);
    signal lhs_V_3_fu_1436_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_31_fu_1430_p2 : STD_LOGIC_VECTOR (159 downto 0);
    signal sext_ln703_15_fu_1444_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_3_fu_1436_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_33_fu_1448_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_11_fu_1464_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_60_fu_1454_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_7_fu_1472_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_32_fu_1483_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_33_fu_1489_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_32_fu_1483_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal r_V_33_fu_1489_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal sext_ln703_16_fu_1495_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal sext_ln703_17_fu_1499_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal r_V_34_fu_1509_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_34_fu_1509_p2 : STD_LOGIC_VECTOR (132 downto 0);
    signal ret_V_34_fu_1503_p2 : STD_LOGIC_VECTOR (133 downto 0);
    signal sext_ln703_18_fu_1515_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal select_ln190_fu_979_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln1118_27_fu_1529_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_35_fu_1533_p0 : STD_LOGIC_VECTOR (52 downto 0);
    signal r_V_35_fu_1533_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_35_fu_1533_p2 : STD_LOGIC_VECTOR (123 downto 0);
    signal sext_ln703_19_fu_1539_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal ret_V_35_fu_1519_p2 : STD_LOGIC_VECTOR (133 downto 0);
    signal ret_V_19_fu_1543_p2 : STD_LOGIC_VECTOR (133 downto 0);
    signal r_V_36_fu_1553_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal lhs_V_4_fu_1559_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_36_fu_1553_p2 : STD_LOGIC_VECTOR (156 downto 0);
    signal sext_ln703_20_fu_1567_p1 : STD_LOGIC_VECTOR (163 downto 0);
    signal lhs_V_4_fu_1559_p3 : STD_LOGIC_VECTOR (163 downto 0);
    signal ret_V_36_fu_1571_p2 : STD_LOGIC_VECTOR (163 downto 0);
    signal tmp_12_fu_1587_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_71_fu_1577_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_8_fu_1595_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_37_fu_1640_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_37_fu_1640_p2 : STD_LOGIC_VECTOR (118 downto 0);
    signal tmp_13_fu_1656_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_74_fu_1646_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_9_fu_1664_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_38_fu_1684_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_38_fu_1684_p2 : STD_LOGIC_VECTOR (118 downto 0);
    signal tmp_14_fu_1700_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_77_fu_1690_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_10_fu_1708_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal mul_ln703_2_fu_1724_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_V_6_fu_1731_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal mul_ln703_3_fu_1741_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_V_39_fu_1748_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_39_fu_1748_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal r_V_40_fu_1754_p3 : STD_LOGIC_VECTOR (117 downto 0);
    signal r_V_41_fu_1776_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_41_fu_1776_p2 : STD_LOGIC_VECTOR (97 downto 0);
    signal sext_ln1192_2_fu_1782_p1 : STD_LOGIC_VECTOR (117 downto 0);
    signal add_ln700_3_fu_1766_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal ret_V_37_fu_1790_p2 : STD_LOGIC_VECTOR (117 downto 0);
    signal trunc_ln1192_10_fu_1786_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln1192_9_fu_1762_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln713_3_fu_1806_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_15_fu_1812_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_83_fu_1796_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_11_fu_1820_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal sext_ln1116_4_fu_1831_p0 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_42_fu_1835_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal r_V_42_fu_1835_p2 : STD_LOGIC_VECTOR (116 downto 0);
    signal trunc_ln708_9_fu_1841_p4 : STD_LOGIC_VECTOR (70 downto 0);
    signal tmp_16_fu_1855_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_86_fu_1851_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal zext_ln415_12_fu_1863_p1 : STD_LOGIC_VECTOR (71 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                I1past_dab1_V <= p_Val2_44_fu_1266_p2;
                I2past_dab1_V <= p_Val2_61_fu_1476_p2;
                I3past_dab1_V <= p_Val2_72_fu_1599_p2;
                V1past_dab1_V <= p_Val2_34_fu_1115_p2;
                V2past_dab1_V <= p_Val2_52_fu_1377_p2;
                b_components_V_0 <= p_Val2_75_fu_1668_p2;
                b_components_V_1 <= p_Val2_78_fu_1712_p2;
                counter1 <= add_ln57_fu_334_p2;
                counter2 <= add_ln66_fu_370_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    I1_dab1_V <= std_logic_vector(unsigned(p_Val2_43_fu_1244_p4) + unsigned(zext_ln415_5_fu_1262_p1));
    I2_dab1_V <= std_logic_vector(unsigned(p_Val2_60_fu_1454_p4) + unsigned(zext_ln415_7_fu_1472_p1));
    I3_dab1_V <= std_logic_vector(unsigned(p_Val2_71_fu_1577_p4) + unsigned(zext_ln415_8_fu_1595_p1));
    V1_dab1_V <= p_Val2_34_fu_1115_p2;
    V2_dab1_V <= p_Val2_52_fu_1377_p2;
    Vp_dab1_V <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln703_2_fu_1724_p0) * signed(p_Val2_34_fu_1115_p2))), 72));
    Vs_dab1_V <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln703_3_fu_1741_p0) * signed(p_Val2_52_fu_1377_p2))), 72));
    add_ln57_fu_334_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(select_ln50_fu_320_p3));
    add_ln66_fu_370_p2 <= std_logic_vector(unsigned(ap_const_lv9_1) + unsigned(nph_fu_356_p3));
    add_ln700_1_fu_563_p2 <= std_logic_vector(unsigned(r_V_12_fu_545_p2) + unsigned(sext_ln700_1_fu_551_p1));
    add_ln700_2_fu_662_p2 <= std_logic_vector(signed(sext_ln1192_4_fu_650_p1) + signed(sext_ln700_2_fu_646_p1));
    add_ln700_3_fu_1766_p2 <= std_logic_vector(unsigned(r_V_39_fu_1748_p2) + unsigned(r_V_40_fu_1754_p3));
    add_ln700_fu_460_p2 <= std_logic_vector(signed(sext_ln1192_fu_448_p1) + signed(sext_ln700_fu_444_p1));
    add_ln703_fu_398_p1 <= i_in_port_model_of_a_V;
    add_ln703_fu_398_p2 <= std_logic_vector(unsigned(b_components_V_0) + unsigned(add_ln703_fu_398_p1));
    add_ln713_1_fu_609_p2 <= std_logic_vector(unsigned(trunc_ln1192_3_fu_555_p1) + unsigned(add_ln713_5_fu_603_p2));
    add_ln713_2_fu_704_p2 <= std_logic_vector(unsigned(trunc_ln1192_6_fu_654_p1) + unsigned(add_ln713_6_fu_698_p2));
    add_ln713_3_fu_1806_p2 <= std_logic_vector(unsigned(trunc_ln1192_10_fu_1786_p1) + unsigned(trunc_ln1192_9_fu_1762_p1));
    add_ln713_4_fu_508_p2 <= std_logic_vector(unsigned(trunc_ln1192_2_fu_484_p1) + unsigned(trunc_ln1192_1_fu_456_p1));
    add_ln713_5_fu_603_p2 <= std_logic_vector(unsigned(trunc_ln1192_5_fu_579_p1) + unsigned(trunc_ln1192_4_fu_559_p1));
    add_ln713_6_fu_698_p2 <= std_logic_vector(unsigned(trunc_ln1192_8_fu_678_p1) + unsigned(trunc_ln1192_7_fu_658_p1));
    add_ln713_fu_514_p2 <= std_logic_vector(unsigned(trunc_ln1192_fu_452_p1) + unsigned(add_ln713_4_fu_508_p2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_out_port_model_to_a_V <= std_logic_vector(unsigned(p_Val2_83_fu_1796_p4) + unsigned(zext_ln415_11_fu_1820_p1));
    i_out_port_model_to_c_V <= std_logic_vector(signed(p_Val2_86_fu_1851_p1) + signed(zext_ln415_12_fu_1863_p1));
    icmp_ln1498_1_fu_885_p2 <= "1" when (ret_V_fu_771_p2 = ap_const_lv48_C00000000000) else "0";
    icmp_ln1498_2_fu_891_p2 <= "1" when (p_Val2_22_fu_735_p3 = p_Val2_19_fu_749_p3) else "0";
    icmp_ln1498_fu_871_p2 <= "1" when (ret_V_fu_771_p2 = ap_const_lv48_400000000000) else "0";
    icmp_ln169_fu_919_p2 <= "1" when (tmp_V_fu_827_p2 = ap_const_lv2_1) else "0";
    icmp_ln173_fu_925_p2 <= "1" when (tmp_V_fu_827_p2 = ap_const_lv2_3) else "0";
    icmp_ln182_fu_953_p2 <= "1" when (tmp_V_5_fu_855_p2 = ap_const_lv2_1) else "0";
    icmp_ln186_fu_959_p2 <= "1" when (tmp_V_5_fu_855_p2 = ap_const_lv2_3) else "0";
    icmp_ln50_fu_314_p2 <= "1" when (unsigned(counter1) < unsigned(ap_const_lv8_EE)) else "0";
    icmp_ln52_fu_328_p2 <= "1" when (unsigned(select_ln50_fu_320_p3) < unsigned(ap_const_lv8_77)) else "0";
    icmp_ln59_fu_350_p2 <= "1" when (unsigned(counter2) < unsigned(ap_const_lv9_115)) else "0";
    icmp_ln61_fu_364_p2 <= "1" when (unsigned(nph_fu_356_p3) < unsigned(ap_const_lv9_9E)) else "0";
    lhs_V_1_fu_1230_p1 <= I1past_dab1_V;
    lhs_V_1_fu_1230_p3 <= (lhs_V_1_fu_1230_p1 & ap_const_lv92_0);
    lhs_V_2_fu_1341_p1 <= V2past_dab1_V;
    lhs_V_2_fu_1341_p3 <= (lhs_V_2_fu_1341_p1 & ap_const_lv92_0);
    lhs_V_3_fu_1436_p1 <= I2past_dab1_V;
    lhs_V_3_fu_1436_p3 <= (lhs_V_3_fu_1436_p1 & ap_const_lv92_0);
    lhs_V_4_fu_1559_p1 <= I3past_dab1_V;
    lhs_V_4_fu_1559_p3 <= (lhs_V_4_fu_1559_p1 & ap_const_lv92_0);
    lhs_V_fu_1079_p1 <= V1past_dab1_V;
    lhs_V_fu_1079_p3 <= (lhs_V_fu_1079_p1 & ap_const_lv92_0);
    mul_ln1193_fu_1136_p1 <= sext_ln1118_12_fu_1021_p0;
    mul_ln1193_fu_1136_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv140_lc_4) * signed(mul_ln1193_fu_1136_p1))), 140));
    mul_ln703_1_fu_865_p1 <= tmp_V_5_fu_855_p2;
    mul_ln703_1_fu_865_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv53_B92F684BDA130) * signed(mul_ln703_1_fu_865_p1))), 53));
    mul_ln703_2_fu_1724_p0 <= tmp_V_fu_827_p2;
    mul_ln703_3_fu_1741_p0 <= tmp_V_6_fu_1731_p2;
    mul_ln703_4_fu_1069_p1 <= ret_V_5_fu_1059_p2;
    mul_ln703_4_fu_1069_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv154_lc_3) * signed(mul_ln703_4_fu_1069_p1))), 154));
    mul_ln703_5_fu_1331_p1 <= ret_V_12_fu_1321_p2;
    mul_ln703_5_fu_1331_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv154_lc_3) * signed(mul_ln703_5_fu_1331_p1))), 154));
    mul_ln703_fu_841_p1 <= tmp_V_fu_827_p2;
    mul_ln703_fu_841_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv60_682AAAAAAAAAAC0) * signed(mul_ln703_fu_841_p1))), 60));
    nph_fu_356_p3 <= 
        counter2 when (icmp_ln59_fu_350_p2(0) = '1') else 
        ap_const_lv9_27;
    or_ln164_fu_905_p2 <= (icmp_ln1498_2_fu_891_p2 or icmp_ln1498_1_fu_885_p2);
    or_ln177_fu_939_p2 <= (icmp_ln173_fu_925_p2 or icmp_ln169_fu_919_p2);
    or_ln190_fu_973_p2 <= (icmp_ln186_fu_959_p2 or icmp_ln182_fu_953_p2);
        p_Val2_11_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_589_p4),72));

    p_Val2_17_fu_688_p4 <= ret_V_24_fu_682_p2(117 downto 46);
    p_Val2_18_fu_722_p2 <= std_logic_vector(unsigned(p_Val2_17_fu_688_p4) + unsigned(zext_ln415_2_fu_718_p1));
    p_Val2_19_fu_749_p3 <= (signbit_1_fu_743_p2 & ap_const_lv46_0);
    p_Val2_22_fu_735_p3 <= (signbit_fu_729_p2 & ap_const_lv46_0);
    p_Val2_23_fu_757_p2 <= std_logic_vector(unsigned(ap_const_lv47_0) - unsigned(p_Val2_19_fu_749_p3));
    p_Val2_25_fu_813_p2 <= std_logic_vector(signed(sext_ln713_fu_797_p1) + signed(zext_ln415_3_fu_809_p1));
    p_Val2_33_fu_1093_p4 <= ret_V_26_fu_1087_p2(163 downto 92);
    p_Val2_34_fu_1115_p2 <= std_logic_vector(unsigned(p_Val2_33_fu_1093_p4) + unsigned(zext_ln415_4_fu_1111_p1));
    p_Val2_43_fu_1244_p4 <= ret_V_29_fu_1238_p2(163 downto 92);
    p_Val2_44_fu_1266_p2 <= std_logic_vector(unsigned(p_Val2_43_fu_1244_p4) + unsigned(zext_ln415_5_fu_1262_p1));
    p_Val2_51_fu_1355_p4 <= ret_V_31_fu_1349_p2(163 downto 92);
    p_Val2_52_fu_1377_p2 <= std_logic_vector(unsigned(p_Val2_51_fu_1355_p4) + unsigned(zext_ln415_6_fu_1373_p1));
        p_Val2_5_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_494_p4),72));

    p_Val2_60_fu_1454_p4 <= ret_V_33_fu_1448_p2(163 downto 92);
    p_Val2_61_fu_1476_p2 <= std_logic_vector(unsigned(p_Val2_60_fu_1454_p4) + unsigned(zext_ln415_7_fu_1472_p1));
    p_Val2_6_fu_532_p2 <= std_logic_vector(signed(p_Val2_5_fu_504_p1) + signed(zext_ln415_fu_528_p1));
    p_Val2_71_fu_1577_p4 <= ret_V_36_fu_1571_p2(163 downto 92);
    p_Val2_72_fu_1599_p2 <= std_logic_vector(unsigned(p_Val2_71_fu_1577_p4) + unsigned(zext_ln415_8_fu_1595_p1));
    p_Val2_74_fu_1646_p4 <= r_V_37_fu_1640_p2(117 downto 46);
    p_Val2_75_fu_1668_p2 <= std_logic_vector(unsigned(p_Val2_74_fu_1646_p4) + unsigned(zext_ln415_9_fu_1664_p1));
    p_Val2_77_fu_1690_p4 <= r_V_38_fu_1684_p2(117 downto 46);
    p_Val2_78_fu_1712_p2 <= std_logic_vector(unsigned(p_Val2_77_fu_1690_p4) + unsigned(zext_ln415_10_fu_1708_p1));
    p_Val2_83_fu_1796_p4 <= ret_V_37_fu_1790_p2(117 downto 46);
        p_Val2_86_fu_1851_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln708_9_fu_1841_p4),72));

    r_V_10_fu_474_p1 <= sext_ln1118_7_fu_470_p1(72 - 1 downto 0);
    r_V_10_fu_474_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv88_DAEB) * signed(r_V_10_fu_474_p1))), 88));
    r_V_11_fu_539_p1 <= sext_ln1118_1_fu_412_p1(72 - 1 downto 0);
    r_V_11_fu_539_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv109_1052A0AAB6) * signed(r_V_11_fu_539_p1))), 109));
    r_V_12_fu_545_p1 <= sext_ln1118_4_fu_430_p0;
    r_V_12_fu_545_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv110_20AA7A7EDE) * signed(r_V_12_fu_545_p1))), 110));
    r_V_13_fu_569_p1 <= sext_ln1118_7_fu_470_p1(72 - 1 downto 0);
    r_V_13_fu_569_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv88_DAA5) * signed(r_V_13_fu_569_p1))), 88));
    r_V_14_fu_634_p1 <= add_ln703_fu_398_p2;
    r_V_14_fu_634_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv88_DAEB) * signed(r_V_14_fu_634_p1))), 88));
    r_V_15_fu_640_p1 <= sext_ln1118_3_fu_426_p0;
    r_V_15_fu_640_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv88_DAA5) * signed(r_V_15_fu_640_p1))), 88));
    r_V_16_fu_672_p1 <= sext_ln1118_6_fu_466_p0;
    r_V_16_fu_672_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv118_33190708F18C) * signed(r_V_16_fu_672_p1))), 118));
    r_V_17_fu_781_p1 <= ret_V_fu_771_p2;
    r_V_17_fu_781_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv104_1CEF684BDA12F60) * signed(r_V_17_fu_781_p1))), 104));
    r_V_18_fu_995_p1 <= sext_ln1118_8_fu_991_p1(72 - 1 downto 0);
    r_V_18_fu_995_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv131_lc_1) * signed(r_V_18_fu_995_p1))), 131));
    r_V_19_fu_1025_p0 <= sext_ln1116_1_fu_1001_p1(59 - 1 downto 0);
    r_V_19_fu_1025_p1 <= sext_ln1118_9_fu_1009_p0;
    r_V_19_fu_1025_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_19_fu_1025_p0) * signed(r_V_19_fu_1025_p1))), 130));
    r_V_20_fu_1049_p1 <= p_Val2_6_fu_532_p2(66 - 1 downto 0);
    r_V_20_fu_1049_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv131_lc_2) * signed(r_V_20_fu_1049_p1))), 131));
    r_V_21_fu_1126_p0 <= select_ln177_fu_945_p3;
    r_V_21_fu_1126_p1 <= sext_ln1118_8_fu_991_p1(72 - 1 downto 0);
    r_V_21_fu_1126_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_21_fu_1126_p0) * signed(r_V_21_fu_1126_p1))), 131));
    r_V_22_fu_1168_p1 <= sext_ln1118_18_fu_1164_p0;
    r_V_22_fu_1168_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv140_lc_5) * signed(r_V_22_fu_1168_p1))), 140));
    r_V_23_fu_1204_p1 <= sext_ln1118_21_fu_1200_p0;
    r_V_23_fu_1204_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv140_lc_5) * signed(r_V_23_fu_1204_p1))), 140));
    r_V_24_fu_1224_p1 <= ret_V_9_fu_1214_p2;
    r_V_24_fu_1224_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv164_lc_3) * signed(r_V_24_fu_1224_p1))), 164));
    r_V_25_fu_1281_p1 <= sext_ln1118_23_fu_1277_p0;
    r_V_25_fu_1281_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(ap_const_lv131_lc_1) * signed(r_V_25_fu_1281_p1))), 131));
    r_V_26_fu_1287_p0 <= sext_ln1116_1_fu_1001_p1(59 - 1 downto 0);
    r_V_26_fu_1287_p1 <= sext_ln1118_25_fu_1152_p0;
    r_V_26_fu_1287_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_26_fu_1287_p0) * signed(r_V_26_fu_1287_p1))), 130));
    r_V_27_fu_1311_p1 <= p_Val2_18_fu_722_p2;
    r_V_27_fu_1311_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv131_lc_2) * signed(r_V_27_fu_1311_p1))), 131));
    r_V_28_fu_1384_p1 <= sext_ln1118_11_fu_1017_p0;
    r_V_28_fu_1384_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv137_lc_6) * signed(r_V_28_fu_1384_p1))), 137));
    r_V_29_fu_1390_p1 <= sext_ln1118_17_fu_1160_p0;
    r_V_29_fu_1390_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv137_lc_6) * signed(r_V_29_fu_1390_p1))), 137));
    r_V_30_fu_1410_p1 <= sext_ln1118_20_fu_1196_p0;
    r_V_30_fu_1410_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv137_lc_6) * signed(r_V_30_fu_1410_p1))), 137));
    r_V_31_fu_1430_p1 <= ret_V_15_fu_1420_p2;
    r_V_31_fu_1430_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv160_lc_3) * signed(r_V_31_fu_1430_p1))), 160));
    r_V_32_fu_1483_p1 <= sext_ln1118_10_fu_1013_p0;
    r_V_32_fu_1483_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_7) * signed(r_V_32_fu_1483_p1))), 133));
    r_V_33_fu_1489_p1 <= sext_ln1118_16_fu_1156_p0;
    r_V_33_fu_1489_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_7) * signed(r_V_33_fu_1489_p1))), 133));
    r_V_34_fu_1509_p1 <= sext_ln1118_19_fu_1192_p0;
    r_V_34_fu_1509_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv133_lc_8) * signed(r_V_34_fu_1509_p1))), 133));
    r_V_35_fu_1533_p0 <= select_ln190_fu_979_p3;
    r_V_35_fu_1533_p1 <= sext_ln1118_27_fu_1529_p0;
    r_V_35_fu_1533_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_35_fu_1533_p0) * signed(r_V_35_fu_1533_p1))), 124));
    r_V_36_fu_1553_p1 <= ret_V_19_fu_1543_p2;
    r_V_36_fu_1553_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv157_lc_3) * signed(r_V_36_fu_1553_p1))), 157));
    r_V_37_fu_1640_p1 <= p_Val2_34_fu_1115_p2;
    r_V_37_fu_1640_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv119_500000000000) * signed(r_V_37_fu_1640_p1))), 119));
    r_V_38_fu_1684_p1 <= p_Val2_52_fu_1377_p2;
    r_V_38_fu_1684_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv119_500000000000) * signed(r_V_38_fu_1684_p1))), 119));
    r_V_39_fu_1748_p1 <= sext_ln1118_2_fu_422_p0;
    r_V_39_fu_1748_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv118_3FEB8BA946A8) * signed(r_V_39_fu_1748_p1))), 118));
    r_V_40_fu_1754_p3 <= (p_Val2_75_fu_1668_p2 & ap_const_lv46_0);
    r_V_41_fu_1776_p1 <= p_Val2_78_fu_1712_p2;
    r_V_41_fu_1776_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv98_3594739) * signed(r_V_41_fu_1776_p1))), 98));
    r_V_42_fu_1835_p1 <= sext_ln1116_4_fu_1831_p0;
    r_V_42_fu_1835_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv117_1FFAE218FF01) * signed(r_V_42_fu_1835_p1))), 117));
    r_V_9_fu_438_p1 <= sext_ln1118_5_fu_434_p0;
    r_V_9_fu_438_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv109_1052A0AAB6) * signed(r_V_9_fu_438_p1))), 109));
    r_V_fu_416_p1 <= sext_ln1118_1_fu_412_p1(72 - 1 downto 0);
    r_V_fu_416_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv109_1057D9D428) * signed(r_V_fu_416_p1))), 109));
    ret_V_12_fu_1321_p2 <= std_logic_vector(signed(sext_ln1118_33_fu_1317_p1) + signed(sext_ln1192_5_fu_1303_p1));
    ret_V_15_fu_1420_p2 <= std_logic_vector(unsigned(ret_V_32_fu_1404_p2) - unsigned(sext_ln703_14_fu_1416_p1));
    ret_V_19_fu_1543_p2 <= std_logic_vector(signed(sext_ln703_19_fu_1539_p1) + signed(ret_V_35_fu_1519_p2));
    ret_V_22_fu_488_p2 <= std_logic_vector(signed(sext_ln1192_1_fu_480_p1) + signed(add_ln700_fu_460_p2));
    ret_V_23_fu_583_p2 <= std_logic_vector(signed(sext_ln1192_3_fu_575_p1) + signed(add_ln700_1_fu_563_p2));
    ret_V_24_fu_682_p2 <= std_logic_vector(unsigned(r_V_16_fu_672_p2) + unsigned(sext_ln700_3_fu_668_p1));
    ret_V_25_fu_1035_p2 <= std_logic_vector(unsigned(r_V_18_fu_995_p2) - unsigned(sext_ln1118_13_fu_1031_p1));
    ret_V_26_fu_1087_p2 <= std_logic_vector(signed(sext_ln703_5_fu_1075_p1) + signed(lhs_V_fu_1079_p3));
    ret_V_27_fu_1142_p2 <= std_logic_vector(unsigned(mul_ln1193_fu_1136_p2) + unsigned(sext_ln703_6_fu_1132_p1));
    ret_V_28_fu_1182_p2 <= std_logic_vector(signed(sext_ln703_8_fu_1178_p1) + signed(sext_ln703_7_fu_1174_p1));
    ret_V_29_fu_1238_p2 <= std_logic_vector(unsigned(r_V_24_fu_1224_p2) + unsigned(lhs_V_1_fu_1230_p3));
    ret_V_30_fu_1297_p2 <= std_logic_vector(signed(sext_ln1118_32_fu_1293_p1) + signed(r_V_25_fu_1281_p2));
    ret_V_31_fu_1349_p2 <= std_logic_vector(signed(sext_ln703_11_fu_1337_p1) + signed(lhs_V_2_fu_1341_p3));
    ret_V_32_fu_1404_p2 <= std_logic_vector(signed(sext_ln703_12_fu_1396_p1) - signed(sext_ln703_13_fu_1400_p1));
    ret_V_33_fu_1448_p2 <= std_logic_vector(signed(sext_ln703_15_fu_1444_p1) + signed(lhs_V_3_fu_1436_p3));
    ret_V_34_fu_1503_p2 <= std_logic_vector(signed(sext_ln703_16_fu_1495_p1) - signed(sext_ln703_17_fu_1499_p1));
    ret_V_35_fu_1519_p2 <= std_logic_vector(unsigned(ret_V_34_fu_1503_p2) - unsigned(sext_ln703_18_fu_1515_p1));
    ret_V_36_fu_1571_p2 <= std_logic_vector(signed(sext_ln703_20_fu_1567_p1) + signed(lhs_V_4_fu_1559_p3));
    ret_V_37_fu_1790_p2 <= std_logic_vector(signed(sext_ln1192_2_fu_1782_p1) + signed(add_ln700_3_fu_1766_p2));
    ret_V_5_fu_1059_p2 <= std_logic_vector(signed(sext_ln1118_15_fu_1055_p1) + signed(sext_ln1193_fu_1041_p1));
    ret_V_9_fu_1214_p2 <= std_logic_vector(signed(sext_ln703_9_fu_1210_p1) + signed(ret_V_28_fu_1182_p2));
    ret_V_fu_771_p2 <= std_logic_vector(unsigned(zext_ln703_fu_763_p1) + unsigned(sext_ln703_1_fu_767_p1));
    select_ln156_fu_877_p3 <= 
        ap_const_lv59_1CEF684BDA12F60 when (icmp_ln1498_fu_871_p2(0) = '1') else 
        p_Val2_25_fu_813_p2;
    select_ln164_1_fu_897_p3 <= 
        ap_const_lv59_0 when (icmp_ln1498_2_fu_891_p2(0) = '1') else 
        ap_const_lv59_631097B425ED0A0;
    select_ln164_fu_911_p3 <= 
        select_ln164_1_fu_897_p3 when (or_ln164_fu_905_p2(0) = '1') else 
        select_ln156_fu_877_p3;
    select_ln177_1_fu_931_p3 <= 
        ap_const_lv60_97D555555555540 when (icmp_ln173_fu_925_p2(0) = '1') else 
        ap_const_lv60_682AAAAAAAAAAC0;
    select_ln177_fu_945_p3 <= 
        select_ln177_1_fu_931_p3 when (or_ln177_fu_939_p2(0) = '1') else 
        mul_ln703_fu_841_p2;
    select_ln190_1_fu_965_p3 <= 
        ap_const_lv53_146D097B425ED0 when (icmp_ln186_fu_959_p2(0) = '1') else 
        ap_const_lv53_B92F684BDA130;
    select_ln190_fu_979_p3 <= 
        select_ln190_1_fu_965_p3 when (or_ln190_fu_973_p2(0) = '1') else 
        mul_ln703_1_fu_865_p2;
    select_ln50_fu_320_p3 <= 
        counter1 when (icmp_ln50_fu_314_p2(0) = '1') else 
        ap_const_lv8_0;
        sext_ln1116_1_fu_1001_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln164_fu_911_p3),130));

    sext_ln1116_4_fu_1831_p0 <= i_in_port_model_of_a_V;
    sext_ln1118_10_fu_1013_p0 <= I1past_dab1_V;
    sext_ln1118_11_fu_1017_p0 <= I1past_dab1_V;
    sext_ln1118_12_fu_1021_p0 <= I1past_dab1_V;
        sext_ln1118_13_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_19_fu_1025_p2),131));

        sext_ln1118_15_fu_1055_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_20_fu_1049_p2),132));

    sext_ln1118_16_fu_1156_p0 <= I2past_dab1_V;
    sext_ln1118_17_fu_1160_p0 <= I2past_dab1_V;
    sext_ln1118_18_fu_1164_p0 <= I2past_dab1_V;
    sext_ln1118_19_fu_1192_p0 <= I3past_dab1_V;
        sext_ln1118_1_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln703_fu_398_p2),109));

    sext_ln1118_20_fu_1196_p0 <= I3past_dab1_V;
    sext_ln1118_21_fu_1200_p0 <= I3past_dab1_V;
    sext_ln1118_23_fu_1277_p0 <= V2past_dab1_V;
    sext_ln1118_25_fu_1152_p0 <= I2past_dab1_V;
    sext_ln1118_27_fu_1529_p0 <= V2past_dab1_V;
    sext_ln1118_2_fu_422_p0 <= i_in_port_model_of_c_V;
        sext_ln1118_32_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_26_fu_1287_p2),131));

        sext_ln1118_33_fu_1317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_27_fu_1311_p2),132));

    sext_ln1118_3_fu_426_p0 <= i_in_port_model_of_c_V;
    sext_ln1118_4_fu_430_p0 <= i_in_port_model_of_c_V;
    sext_ln1118_5_fu_434_p0 <= i_in_port_model_of_c_V;
    sext_ln1118_6_fu_466_p0 <= b_components_V_1;
    sext_ln1118_7_fu_470_p0 <= b_components_V_1;
        sext_ln1118_7_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_7_fu_470_p0),88));

    sext_ln1118_8_fu_991_p0 <= V1past_dab1_V;
        sext_ln1118_8_fu_991_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_8_fu_991_p0),131));

    sext_ln1118_9_fu_1009_p0 <= I1past_dab1_V;
        sext_ln1192_1_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_10_fu_474_p2),110));

        sext_ln1192_2_fu_1782_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_41_fu_1776_p2),118));

        sext_ln1192_3_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_13_fu_569_p2),110));

        sext_ln1192_4_fu_650_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_15_fu_640_p2),89));

        sext_ln1192_5_fu_1303_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_30_fu_1297_p2),132));

        sext_ln1192_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_9_fu_438_p2),110));

        sext_ln1193_fu_1041_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_25_fu_1035_p2),132));

        sext_ln700_1_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_11_fu_539_p2),110));

        sext_ln700_2_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_14_fu_634_p2),89));

        sext_ln700_3_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln700_2_fu_662_p2),118));

        sext_ln700_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_fu_416_p2),110));

        sext_ln703_11_fu_1337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln703_5_fu_1331_p2),164));

        sext_ln703_12_fu_1396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_28_fu_1384_p2),138));

        sext_ln703_13_fu_1400_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_29_fu_1390_p2),138));

        sext_ln703_14_fu_1416_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_30_fu_1410_p2),138));

        sext_ln703_15_fu_1444_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_31_fu_1430_p2),164));

        sext_ln703_16_fu_1495_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_32_fu_1483_p2),134));

        sext_ln703_17_fu_1499_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_33_fu_1489_p2),134));

        sext_ln703_18_fu_1515_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_34_fu_1509_p2),134));

        sext_ln703_19_fu_1539_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_35_fu_1533_p2),134));

        sext_ln703_1_fu_767_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_23_fu_757_p2),48));

        sext_ln703_20_fu_1567_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_36_fu_1553_p2),164));

        sext_ln703_5_fu_1075_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln703_4_fu_1069_p2),164));

        sext_ln703_6_fu_1132_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_21_fu_1126_p2),140));

        sext_ln703_7_fu_1174_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_27_fu_1142_p2),141));

        sext_ln703_8_fu_1178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_22_fu_1168_p2),141));

        sext_ln703_9_fu_1210_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_23_fu_1204_p2),141));

        sext_ln713_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_787_p4),59));

    signbit_1_fu_743_p2 <= (xor_ln78_fu_388_p2 and xor_ln72_fu_382_p2);
    signbit_fu_729_p2 <= (icmp_ln61_fu_364_p2 and icmp_ln52_fu_328_p2);
    tmp_10_fu_1365_p3 <= ret_V_31_fu_1349_p2(91 downto 91);
    tmp_11_fu_1464_p3 <= r_V_31_fu_1430_p2(91 downto 91);
    tmp_12_fu_1587_p3 <= r_V_36_fu_1553_p2(91 downto 91);
    tmp_13_fu_1656_p3 <= r_V_37_fu_1640_p2(45 downto 45);
    tmp_14_fu_1700_p3 <= r_V_38_fu_1684_p2(45 downto 45);
    tmp_15_fu_1812_p3 <= add_ln713_3_fu_1806_p2(45 downto 45);
    tmp_16_fu_1855_p3 <= r_V_42_fu_1835_p2(45 downto 45);
    tmp_1_fu_494_p4 <= ret_V_22_fu_488_p2(109 downto 46);
    tmp_2_fu_520_p3 <= add_ln713_fu_514_p2(45 downto 45);
    tmp_3_fu_589_p4 <= ret_V_23_fu_583_p2(109 downto 46);
    tmp_4_fu_615_p3 <= add_ln713_1_fu_609_p2(45 downto 45);
    tmp_5_fu_710_p3 <= add_ln713_2_fu_704_p2(45 downto 45);
    tmp_6_fu_787_p4 <= r_V_17_fu_781_p2(103 downto 46);
    tmp_7_fu_801_p3 <= r_V_17_fu_781_p2(45 downto 45);
    tmp_8_fu_1103_p3 <= ret_V_26_fu_1087_p2(91 downto 91);
    tmp_9_fu_1254_p3 <= ret_V_29_fu_1238_p2(91 downto 91);
    tmp_V_5_fu_855_p2 <= std_logic_vector(unsigned(zext_ln153_fu_847_p1) - unsigned(zext_ln153_1_fu_851_p1));
    tmp_V_6_fu_1731_p2 <= std_logic_vector(unsigned(zext_ln153_1_fu_851_p1) - unsigned(zext_ln153_fu_847_p1));
    tmp_V_fu_827_p2 <= std_logic_vector(unsigned(zext_ln152_fu_819_p1) - unsigned(zext_ln152_1_fu_823_p1));
    trunc_ln1192_10_fu_1786_p1 <= r_V_41_fu_1776_p2(46 - 1 downto 0);
    trunc_ln1192_1_fu_456_p1 <= r_V_fu_416_p2(46 - 1 downto 0);
    trunc_ln1192_2_fu_484_p1 <= r_V_10_fu_474_p2(46 - 1 downto 0);
    trunc_ln1192_3_fu_555_p1 <= r_V_12_fu_545_p2(46 - 1 downto 0);
    trunc_ln1192_4_fu_559_p1 <= r_V_11_fu_539_p2(46 - 1 downto 0);
    trunc_ln1192_5_fu_579_p1 <= r_V_13_fu_569_p2(46 - 1 downto 0);
    trunc_ln1192_6_fu_654_p1 <= r_V_15_fu_640_p2(46 - 1 downto 0);
    trunc_ln1192_7_fu_658_p1 <= r_V_14_fu_634_p2(46 - 1 downto 0);
    trunc_ln1192_8_fu_678_p1 <= r_V_16_fu_672_p2(46 - 1 downto 0);
    trunc_ln1192_9_fu_1762_p1 <= r_V_39_fu_1748_p2(46 - 1 downto 0);
    trunc_ln1192_fu_452_p1 <= r_V_9_fu_438_p2(46 - 1 downto 0);
    trunc_ln708_9_fu_1841_p4 <= r_V_42_fu_1835_p2(116 downto 46);
    x_out_b_0_V <= p_Val2_6_fu_532_p2;
    x_out_b_1_V <= std_logic_vector(signed(p_Val2_11_fu_599_p1) + signed(zext_ln415_1_fu_623_p1));
    x_out_b_2_V <= p_Val2_18_fu_722_p2;
    xor_ln72_fu_382_p2 <= (icmp_ln52_fu_328_p2 xor ap_const_lv1_1);
    xor_ln78_fu_388_p2 <= (icmp_ln61_fu_364_p2 xor ap_const_lv1_1);
    zext_ln152_1_fu_823_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln72_fu_382_p2),2));
    zext_ln152_fu_819_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln52_fu_328_p2),2));
    zext_ln153_1_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln61_fu_364_p2),2));
    zext_ln153_fu_847_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln78_fu_388_p2),2));
    zext_ln415_10_fu_1708_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_1700_p3),72));
    zext_ln415_11_fu_1820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_1812_p3),72));
    zext_ln415_12_fu_1863_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_1855_p3),72));
    zext_ln415_1_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_615_p3),72));
    zext_ln415_2_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_710_p3),72));
    zext_ln415_3_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_801_p3),59));
    zext_ln415_4_fu_1111_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_1103_p3),72));
    zext_ln415_5_fu_1262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_1254_p3),72));
    zext_ln415_6_fu_1373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1365_p3),72));
    zext_ln415_7_fu_1472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_1464_p3),72));
    zext_ln415_8_fu_1595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_1587_p3),72));
    zext_ln415_9_fu_1664_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_1656_p3),72));
    zext_ln415_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_520_p3),72));
    zext_ln703_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_22_fu_735_p3),48));
end behav;
